---
# list of applications to install
local_home: "{{ lookup('env','HOME') }}"
work_dir: "{{ local_home }}/Work"

# homebrew applications
applications:
  # shell utils
  - autojump
  - zsh
  - tree
  - httpie
  - curl
  - wget
  - ctags
  - tmux
  - ag
  - fzf
  - git
  - git-lfs
  - tig

  # editor
  - vim
  - neovim

  # lang
  - go
  - rbenv
  - pyenv
  - pyenv-virtualenv

  # dependencies
  - postgresql
  - qt@5.5

# homebrew cask applications
cask_applications:
  - google-chrome
  - firefoxdeveloperedition
  - slack
  - iterm2
  - docker
  - emacs
  - 1password
  - spotify
  - sublime-text
  - spectacle

cask_fonts:
  - font-inconsolata
  - font-inconsolata-g-for-powerline
  - font-fira-mono
  - font-fira-mono-for-powerline
  - font-fira-code
  - font-source-code-pro
  - font-source-code-pro-for-powerline
  - font-fontawesome
  - font-materialdesignicons-webfont
  - font-hack
  - font-meslo-lg
  - font-meslo-for-powerline
