---
# getting scm_breeze

- name: cloning scm-breeze
  git:
    repo: https://github.com/scmbreeze/scm_breeze.git
    dest: "{{local_home}}/.scm_breeze"

- name: installing scm-breeze
  command: "{{local_home}}/.scm_breeze/install.sh"
